# Generated by Django 5.1.5 on 2025-07-31 13:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('image', models.ImageField(upload_to='banners/')),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='cards/')),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('when_sent', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('replied', models.BooleanField(default=False)),
                ('when_replied', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_contact', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('recent_contact', models.DateTimeField(blank=True, null=True)),
                ('interest', models.CharField(max_length=100)),
                ('first_session', models.DateTimeField(blank=True, null=True)),
                ('custnotes', models.TextField(blank=True, null=True, verbose_name='Customer General Notes')),
                ('magic_link_token', models.CharField(blank=True, max_length=100, null=True)),
                ('magic_link_expires', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('kp_notes', models.TextField(blank=True, null=True, verbose_name='Key Points')),
                ('fu_notes', models.TextField(blank=True, null=True, verbose_name='Follow Up Actions')),
                ('invoiced', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='mainapp.customerprofile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
