# Generated by Django 5.1.5 on 2025-08-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentmedia',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
