# Generated by Django 5.1.5 on 2025-08-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_main', '0002_remove_contentmedia_thumbnail_content_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('BANNER', 'Banners'), ('CARD', 'Product Cards'), ('ABOUT', 'About Us'), ('FAQ', 'Frequently Asked Questions'), ('PRIVACY', 'Privacy Policies'), ('TERMS', 'Terms of Service')], default='CARD', max_length=50),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
