name: dyvlife_stack

services:
  postgresdb:
    image: postgres:17.2-alpine3.21
    container_name: dyvlife_postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env

  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dyvlife_django
    depends_on:
      - postgresdb
    volumes:
      - static_data:/project/staticfiles
      - media_data:/project/mediafiles
    env_file:
      - ./.env

  nginx:
    image: nginx:1.27.3-alpine-slim
    container_name: dyvlife_nginx
    ports:
      - "8001:80"
    networks:
      - default
      - npm-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_data:/static:ro
      - media_data:/media:ro
    depends_on:
      - django

volumes:
  postgres_data:
  static_data:
  media_data:

networks:
  npm-network:
    external: true
