name: danet_project

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: danet_project_django
    restart: unless-stopped
    depends_on:
      - postgresdb
    volumes:
      - static_data:/project/staticfiles
      - media_data:/project/mediafiles
    env_file:
      - ./.env

  nginx:
    image: nginx:1.27.3-alpine-slim
    container_name: danet_project_nginx
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_data:/static:ro
      - media_data:/media:ro
    depends_on:
      - django

volumes:
  static_data:
  media_data:
